"""각 게임 단계의 자동 진행 타이머 길이(초). 값만 바꾸면 전체 진행 속도가 조정된다."""

ROLE_ASSIGNMENT_SECONDS = 15
DAY_DISCUSSION_SECONDS = 90
DAY_VOTE_SECONDS = 45
FINAL_DEFENSE_SECONDS = 30
EXECUTION_VOTE_SECONDS = 20
NIGHT_ACTION_SECONDS = 30
